default_stages: [pre-commit, manual]

# exclude: Exclude files from being checked
# use pipes to exclude multiple files or directories
exclude: |
  (?x)^(
    .venv/.*|
    .vscode/.*|
  )$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml

  - repo: https://github.com/python-poetry/poetry
    rev: 2.1.1
    hooks:
      - id: poetry-check

  - repo: https://github.com/aristanetworks/j2lint.git
    rev: v1.1.0
    hooks:
    - id: j2lint
      args: [--ignore, S3, S6, S7, V1, --]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
      - id: ruff
        args: ["check", "--select", "I", "--fix"]
      - id: ruff-format

  - repo: https://github.com/asottile/pyupgrade
    rev: "v3.19.1"
    hooks:
      - id: pyupgrade
        args: [--py310-plus]
